bldr:
    profiles:
        default:
            description: 'Development Profile'
            tasks:
                - prepare
                - lint
                - phpcs
                - test
        test:
            description: "Test Profile"
            tasks:
                - testDev
        watch:
            description: "Watch Profile"
            tasks:
                - testDev
                - watch
        server:
            description: Starts a server and waits for a bit. Then kills it.
            tasks:
                - server
        mysql:
            description: Tests the MysqlExtension calls
            tasks:
                - mysql
        misc:
            description: Tests the MiscellaneousExtension calls
            tasks:
                - misc
        release:
            description: Releases a new Tag of Bldr, and builds the phar
            tasks:
                - release
                - buildPhar
